#!/bin/sh

echo "Weblate domain:"
read domain
echo "Weblate title:"
read title
echo "Sentry DNS:"
read sentry
echo "Matomo site id:"
read matomo
echo "Matomo token:"
read matomo_token
echo "Munin allow:"
read munin

smtp_pass=$(openssl rand -hex 32)

cat > /etc/weblate-bootstrap <<EOT
WEBLATE_DOMAIN="$domain"
WEBLATE_TITLE="$title"
WEBLATE_SECRET=$(openssl rand -hex 32)
WEBLATE_SENTRY="$sentry"

# Matomo
MATOMO_SITE="$matomo"
MATOMO_TOKEN="$matomo_token"

# Exim
EXIM_PASS=$smtp_pass
# $(openssl passwd -6 "$smtp_pass")

# Postgresql
POSTGRES_PASS=$(openssl rand -hex 32)

# Munin
MUNIN_ALLOW="$munin"
EOT
