#!/bin/sh
sed -i s/bullseye/bookworm/ /etc/apt/sources.list /etc/apt/sources.list.d/*.list
apt update
apt purge postgresql-13 postgresql-client-13 postgresql-11 postgresql-client-11
apt full-upgrade
apt autoremove
