#!/bin/sh

# Update apt source
rm -f /etc/apt/sources.list /etc/apt/sources.list.d/hetzner*
cat > /etc/apt/sources.list.d/debian.sources << EOT
Types: deb
URIs: https://deb.debian.org/debian
Suites: trixie trixie-updates
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: https://security.debian.org/debian-security
Suites: trixie-security
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOT
if [ -f /etc/apt/sources.list.d/docker.list ]; then
    sed -i s/bookworm/trixie/ /etc/apt/sources.list.d/docker.list
fi

apt update
apt full-upgrade -y
apt autoremove --purge -y
