#!/bin/sh

set -e

. /etc/weblate-bootstrap

# Munin
mkdir -p /etc/munin/plugin-conf.d/
cat > /etc/munin/plugin-conf.d/postgres <<EOT
[postgres_*]
user postgres
env.PGUSER postgres
EOT

# Plugins
mkdir -p /usr/share/munin/plugins/
cd /usr/share/munin/plugins/
wget https://raw.githubusercontent.com/munin-monitoring/contrib/master/plugins/redis/redis_
wget https://raw.githubusercontent.com/WeblateOrg/munin/master/weblate
chmod +x redis_ weblate
cat > /etc/munin/plugin-conf.d/weblate_servers <<EOT
[weblate]
env.SERVER https://$WEBLATE_DOMAIN/
env.KEY $(sudo -u weblate /home/weblate/weblate-env/bin/weblate shell -c 'from weblate.auth.models import User; user = User.objects.create(username="monitor"); print(user.auth_token.key)')
EOT

# Install and configure munin
# The mkdir is needed on Ubuntu (used for CI)
mkdir /run/munin/
chmod 777 /run/munin/
apt install -y munin-node munin-plugins-extra libdbd-pg-perl libwww-perl || systemctl status munin-node.service

sed -i "/allow.*::1/ a allow ^$MUNIN_ALLOW\$" /etc/munin/munin-node.conf
systemctl restart munin-node
