#!/bin/sh

set -e

if [ -n "$1" ]; then
	WEBLATE_GRAYLOG_TOKEN="$1"
else
	# shellcheck disable=SC1091
	. /etc/weblate-bootstrap
fi

# Install package
wget https://packages.graylog2.org/repo/packages/graylog-sidecar-repository_1-5_all.deb
dpkg -i graylog-sidecar-repository_1-5_all.deb
rm graylog-sidecar-repository_1-5_all.deb
apt-get update
apt-get install -y graylog-sidecar

# Configure
sed -i "s@^.\?server_url:.*@server_url: http://172.16.0.78:9000/api/@" /etc/graylog/sidecar/sidecar.yml
sed -i "s@^server_api_token:.*@server_api_token: $WEBLATE_GRAYLOG_TOKEN@" /etc/graylog/sidecar/sidecar.yml
sed -i "s@^#node_id: @node_id: @" /etc/graylog/sidecar/sidecar.yml

# Start service
graylog-sidecar -service install
systemctl enable graylog-sidecar
systemctl start graylog-sidecar
