#!/bin/sh

set -e 

cd /tmp

# Stop web
systemctl stop uwsgi.service 

WEBLATE_HOME=~weblate

# Wait for celery to process all jobs
while sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate celery_queues | grep ': [^0]' ; do
    sleep 1
done

# Stop celery
systemctl stop celery-weblate.service

PYVER=$(python3 -c 'import sys; print("{}.{}".format(*sys.version_info[:2]))')

# Upgrade modules
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/pip install -U pip
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/pip install --upgrade-strategy eager -U Weblate[Unicode,YAML,PHP,Subtitles,OCR,MSTerminology,Amazon,Postgres,Antispam] wllegal

# Adjust configuration
if [ "x$1" != "x--nodiff" ] ; then
vimdiff $WEBLATE_HOME/weblate-env/lib/python$PYVER/site-packages/weblate/settings_example.py $WEBLATE_HOME/weblate-env/lib/python$PYVER/site-packages/weblate/settings.py
fi
cp $WEBLATE_HOME/weblate-env/lib/python$PYVER/site-packages/weblate/examples/celery-weblate.conf /etc/default/celery-weblate

# Migrate database, compile gettext and collect static files
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate migrate
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate collectstatic --noinput

# Start the services
systemctl start celery-weblate.service 
systemctl start uwsgi.service

# Upgrade munin plugin
if [ -d /usr/share/munin/plugins ] ; then
    wget -O - https://raw.githubusercontent.com/WeblateOrg/munin/master/weblate > /usr/share/munin/plugins/weblate
    wget -O - https://raw.githubusercontent.com/WeblateOrg/munin/master/ksm > /usr/share/munin/plugins/ksm
fi

# Upgrade fail2ban
if [ -d /etc/fail2ban/filter.d/ ] ; then
    sudo -u weblate sh -c "cd $WEBLATE_HOME/fail2ban && git pull"
    ln -sf $WEBLATE_HOME/fail2ban/filter.d/* /etc/fail2ban/filter.d/
    ln -sf $WEBLATE_HOME/fail2ban/jail.d/* /etc/fail2ban/jail.d/
    systemctl restart fail2ban.service
fi
