#!/bin/sh

set -e 

cd /tmp

# Stop web
systemctl stop uwsgi.service 

# Wait for celery to process all jobs
while sudo -u weblate /home/weblate/weblate-env/bin/weblate celery_queues | grep ': [^0]' ; do
    sleep 1
done

# Stop celery
systemctl stop celery-weblate.service

PYVER=$(python3 -c 'import sys; print("{}.{}".format(*sys.version_info[:2]))')

# Upgrade modules
sudo -u weblate /home/weblate/weblate-env/bin/pip install -U Weblate psycopg2-binary ruamel.yaml aeidon boto3 zeep chardet tesserocr phply
sudo -u weblate /home/weblate/weblate-env/bin/pip install https://github.com/WeblateOrg/hosted/archive/master.zip

# Adjust configuration
if [ "x$1" != "x--nodiff" ] ; then
vimdiff /home/weblate/weblate-env/lib/python$PYVER/site-packages/weblate/settings_example.py /home/weblate/weblate-env/lib/python$PYVER/site-packages/weblate/settings.py
fi
cp /home/weblate/weblate-env/lib/python$PYVER/site-packages/weblate/examples/celery-weblate.conf /etc/default/celery-weblate

# Migrate database, compile gettext and collect static files
sudo -u weblate /home/weblate/weblate-env/bin/weblate migrate
sudo -u weblate /home/weblate/weblate-env/bin/weblate collectstatic --noinput
sudo -u weblate /home/weblate/weblate-env/bin/weblate compilemessages

# Start the services
systemctl start celery-weblate.service 
systemctl start uwsgi.service

# Upgrade munin plugin
wget -O - https://raw.githubusercontent.com/WeblateOrg/munin/master/weblate > /usr/share/munin/plugins/weblate

# Upgrade fail2ban
sudo -u weblate sh -c "cd /home/weblate/fail2ban && git pull"
ln -sf /home/weblate/fail2ban/filter.d/* /etc/fail2ban/filter.d/
ln -sf /home/weblate/fail2ban/jail.d/* /etc/fail2ban/jail.d/
