#!/bin/sh

set -e 

cd /tmp

# Stop web
systemctl stop uwsgi.service 

WEBLATE_HOME=~weblate

PYVER=$(python3 -c 'import sys; print("{}.{}".format(*sys.version_info[:2]))')

if [ -d "$WEBLATE_HOME/weblate" ] ; then 
    WEBLATE_DIR="$WEBLATE_HOME/weblate"
    WEBLATE_PKG="$WEBLATE_DIR"
    PIP_ARGS="--editable"
else
    WEBLATE_DIR="$WEBLATE_HOME/weblate-env/lib/python$PYVER/site-packages"
    WEBLATE_PKG="Weblate"
    PIP_ARGS=""
fi

# Wait for celery to process all jobs
while sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate celery_queues | grep ': [^0]' ; do
    sleep 1
done

# Stop celery
systemctl stop celery-weblate.service

# Upgrade modules
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/pip install -U pip
if [ "$WEBLATE_DIR" = "$WEBLATE_HOME/weblate" ] ; then
    sudo -u weblate sh -c "cd $WEBLATE_DIR; git pull"
fi
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/pip install --upgrade-strategy eager --upgrade $PIP_ARGS $WEBLATE_PKG[Unicode,YAML,PHP,Subtitles,OCR,MSTerminology,Amazon,Postgres,Antispam] wllegal

# Adjust configuration
if [ "x$1" != "x--nodiff" ] ; then
vimdiff $WEBLATE_DIR/weblate/settings_example.py $WEBLATE_DIR/weblate/settings.py
fi
cp $WEBLATE_DIR/weblate/examples/celery-weblate.conf /etc/default/celery-weblate

# Migrate database, compile gettext and collect static files
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate migrate
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate collectstatic --noinput
if [ "$WEBLATE_DIR" = "$WEBLATE_HOME/weblate" ] ; then
    sudo -u weblate sh -c "cd $WEBLATE_DIR; $WEBLATE_HOME/weblate-env/bin/weblate compilemessages"
    if [ -d $WEBLATE_HOME/hosted ] ; then
        sudo -u weblate sh -c "cd $WEBLATE_HOME/hosted; git pull -q; $WEBLATE_HOME/weblate-env/bin/weblate compilemessages"
    fi
fi
# Track deploy at Sentry
sudo -u weblate $WEBLATE_HOME/weblate-env/bin/weblate sentry_deploy

# Start the services
systemctl start celery-weblate.service 
systemctl start uwsgi.service

# Upgrade munin plugin
if [ -d /usr/share/munin/plugins ] ; then
    wget -O - https://raw.githubusercontent.com/WeblateOrg/munin/master/weblate > /usr/share/munin/plugins/weblate
    wget -O - https://raw.githubusercontent.com/WeblateOrg/munin/master/ksm > /usr/share/munin/plugins/ksm
fi

# Upgrade fail2ban
if [ -d /etc/fail2ban/filter.d/ ] ; then
    sudo -u weblate sh -c "cd $WEBLATE_HOME/fail2ban && git pull"
    ln -sf $WEBLATE_HOME/fail2ban/filter.d/* /etc/fail2ban/filter.d/
    ln -sf $WEBLATE_HOME/fail2ban/jail.d/* /etc/fail2ban/jail.d/
    systemctl reload fail2ban.service
fi
